Return-Path: <linux-tegra-owner@vger.kernel.org>
X-Original-To: lists+linux-tegra@lfdr.de
Delivered-To: lists+linux-tegra@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 2D51DA555A
	for <lists+linux-tegra@lfdr.de>; Mon,  2 Sep 2019 13:56:21 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1730435AbfIBL4U (ORCPT <rfc822;lists+linux-tegra@lfdr.de>);
        Mon, 2 Sep 2019 07:56:20 -0400
Received: from mx2.suse.de ([195.135.220.15]:56874 "EHLO mx1.suse.de"
        rhost-flags-OK-OK-OK-FAIL) by vger.kernel.org with ESMTP
        id S1730291AbfIBL4U (ORCPT <rfc822;linux-tegra@vger.kernel.org>);
        Mon, 2 Sep 2019 07:56:20 -0400
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.220.254])
        by mx1.suse.de (Postfix) with ESMTP id 2066BAD17;
        Mon,  2 Sep 2019 11:56:19 +0000 (UTC)
Date:   Mon, 02 Sep 2019 13:56:19 +0200
Message-ID: <s5htv9uykrg.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Thierry Reding <thierry.reding@gmail.com>
Cc:     Josh Boyer <jwboyer@kernel.org>, linux-firmware@kernel.org,
        Mikko Perttunen <mperttunen@nvidia.com>,
        linux-tegra@vger.kernel.org
Subject: Re: [PATCH] Add symlinks for Tegra VIC firmware binaries
In-Reply-To: <20190902074718.GB930@ulmo>
References: <20190830103350.8273-1-thierry.reding@gmail.com>
        <s5h1rx2270k.wl-tiwai@suse.de>
        <20190902074718.GB930@ulmo>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII
Sender: linux-tegra-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-tegra.vger.kernel.org>
X-Mailing-List: linux-tegra@vger.kernel.org

On Mon, 02 Sep 2019 09:47:18 +0200,
Thierry Reding wrote:
> 
> On Fri, Aug 30, 2019 at 02:05:15PM +0200, Takashi Iwai wrote:
> > On Fri, 30 Aug 2019 12:33:50 +0200,
> > Thierry Reding wrote:
> > > 
> > > I've noticed that the current Link: mechanism completely ignores the
> > > target part of the link. Was this intended to allow creating symlinks
> > > dynamically when copying the firmware, rather than just copying any
> > > existing symlinks themselves?
> > 
> > That's a kind of intentional; the script doesn't validate by itself
> > but just installs to the target directory.  And the cp -d option
> > preserves the symlink as-is, so it should work as long as the original
> > symlink is correctly set up.
> 
> Perhaps some code could be added to create the symlinks if the "-> foo"
> part was specified and no symlink exists.

Yeah, it sounds like a good idea.

> Not a big deal, I just think it's a bit redundant to basically have all
> the symlink information in the WHENCE file and in the filesystem. That's
> especially annoying if both get out of sync.
> 
> I'll volunteer to write that patch if you think it'd be a worthwhile
> addition.

I'm for it but leave the decision to Josh :)


Thanks!

Takashi
