Return-Path: <linux-tegra-owner@vger.kernel.org>
X-Original-To: lists+linux-tegra@lfdr.de
Delivered-To: lists+linux-tegra@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id A49788BB6C
	for <lists+linux-tegra@lfdr.de>; Tue, 13 Aug 2019 16:25:19 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1728045AbfHMOZT (ORCPT <rfc822;lists+linux-tegra@lfdr.de>);
        Tue, 13 Aug 2019 10:25:19 -0400
Received: from foss.arm.com ([217.140.110.172]:37918 "EHLO foss.arm.com"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S1728026AbfHMOZT (ORCPT <rfc822;linux-tegra@vger.kernel.org>);
        Tue, 13 Aug 2019 10:25:19 -0400
Received: from usa-sjc-imap-foss1.foss.arm.com (unknown [10.121.207.14])
        by usa-sjc-mx-foss1.foss.arm.com (Postfix) with ESMTP id 6B6F4344;
        Tue, 13 Aug 2019 07:25:18 -0700 (PDT)
Received: from big-swifty.misterjones.org (unknown [172.31.20.19])
        by usa-sjc-imap-foss1.foss.arm.com (Postfix) with ESMTPSA id C0EBD3F706;
        Tue, 13 Aug 2019 07:25:14 -0700 (PDT)
Date:   Tue, 13 Aug 2019 15:25:06 +0100
Message-ID: <86blwtnnwd.wl-maz@kernel.org>
From:   Marc Zyngier <maz@kernel.org>
To:     Dmitry Osipenko <digetx@gmail.com>
Cc:     Thierry Reding <thierry.reding@gmail.com>,
        Jonathan Hunter <jonathanh@nvidia.com>,
        Peter De Schrijver <pdeschrijver@nvidia.com>,
        Thomas Gleixner <tglx@linutronix.de>,
        Jason Cooper <jason@lakedaemon.net>,
        linux-tegra@vger.kernel.org, linux-kernel@vger.kernel.org
Subject: Re: [PATCH v1 1/2] irqchip/tegra: Remove everything related to COP
In-Reply-To: <20190811183044.13925-1-digetx@gmail.com>
References: <20190811183044.13925-1-digetx@gmail.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI-EPG/1.14.7 (Harue)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 EasyPG/1.0.0 Emacs/26
 (aarch64-unknown-linux-gnu) MULE/6.0 (HANACHIRUSATO)
Organization: Approximate
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
Sender: linux-tegra-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-tegra.vger.kernel.org>
X-Mailing-List: linux-tegra@vger.kernel.org

On Sun, 11 Aug 2019 19:30:43 +0100,
Dmitry Osipenko <digetx@gmail.com> wrote:
> 
> There is no point in touching of the COP (ARM7TDMI auxiliary boot/firmware
> CPU) because COP's interrupts should be related only to an old multimedia
> firmware that is not applicable to the upstream kernel. Hence let's remove
> everything related to the COP, for consistency.

We've had that exact discussion a few weeks ago, and I objected to
this change as there is no possible way you can know for sure people
don't use mainline with an old firmware. The whole point of the
firmware is to be an abstraction for the kernel, for better or worse.

If you really want to do something useful here, consider detecting
such firmware (even better, detect the new ones that don't require
this stuff) and document the various requirements. At least we'll know
where we stand, because the changes you're making are just as random
as what we have so far.

Thanks,

	M.

-- 
Jazz is not dead, it just smells funny.
